import localFont from "next/font/local";
import "./globals.css";

const nunito = localFont({
  src: [{
    path: './fonts/Nunito-Regular.woff',
    weight: '400',
    style: 'normal'
  }]
});

export const metadata = {
  title: "Eduardo Tacorda",
  description: "Generated by Eduardo Tacorda",
};

export default function RootLayout({ children }) {
  
  return (
    <html data-theme='light' lang="en" className="scroll-smooth">
      <body className={`${nunito.className} antialiased`} >
        {children}
      </body>
    </html>
  );
}